### ISSUE TITLE
How to export rendered rgba/normals/depth image with --no-gui option enabled

### ISSUE THREAD

**Issue by Qinerrrrr** [Zielon/INSTA#10]
Thanks for you work. How to save rendered rgba/normals/depth image with --no-gui option enabled. I dont see any save functions in main train/render loop.

**Comment by Zielon** [comment]
In the config you can use `  "render_from_snapshot": false      # For --no-gui option to directly render sequences`

**Comment by Qinerrrrr** [comment]
> In the config, you can use `"render_from_snapshot": false # For --no-gui option to directly render sequences`

Thanks for your quick reply! But it still not work.
I try this code:
`
./build/rta --config insta.json --scene data/mydata --height 512 --width 512 --no-gui
`
with
` "render_from_snapshot": false `

The terminal keeps looping and outputting the following content. But no files (images or models) are being saved.

`15:06:25 INFO     iteration=33000 loss=0.00426574
15:06:25 INFO     iteration=33000 loss=0.00426574
15:06:25 INFO     iteration=33000 loss=0.00426574
15:06:26 INFO     iteration=33000 loss=0.00426574
15:06:26 INFO     iteration=33000 loss=0.00426574
15:06:26 INFO     iteration=33000 loss=0.00426574
15:06:26 INFO     iteration=33000 loss=0.00426574
15:06:26 INFO     iteration=33000 loss=0.00426574
15:06:26 INFO     iteration=33000 loss=0.00426574
15:06:26 INFO     iteration=33000 loss=0.00426574
15:06:26 INFO     iteration=33000 loss=0.00426574
15:06:27 INFO     iteration=33000 loss=0.00426574
15:06:27 INFO     iteration=33000 loss=0.00426574
15:06:27 INFO     iteration=33000 loss=0.00426574
15:06:27 INFO     iteration=33000 loss=0.00426574
15:06:27 INFO     iteration=33000 loss=0.00426574
15:06:27 INFO     iteration=33000 loss=0.00426574
15:06:27 INFO     iteration=33000 loss=0.00426574
15:06:28 INFO     iteration=33000 loss=0.00426574
15:06:28 INFO     iteration=33000 loss=0.00426574
15:06:28 INFO     iteration=33000 loss=0.00426574
15:06:28 INFO     iteration=33000 loss=0.00426574
15:06:28 INFO     iteration=33000 loss=0.00426574
15:06:28 INFO     iteration=33000 loss=0.00426574
15:06:28 INFO     iteration=33000 loss=0.00426574
15:06:28 INFO     iteration=33000 loss=0.00426574
15:06:29 INFO     iteration=33000 loss=0.00426574
15:06:29 INFO     iteration=33000 loss=0.00426574
15:06:29 INFO     iteration=33000 loss=0.00426574
15:06:29 INFO     iteration=33000 loss=0.00426574
15:06:29 INFO     iteration=33000 loss=0.00426574
15:06:29 INFO     iteration=33000 loss=0.00426574
15:06:29 INFO     iteration=33000 loss=0.00426574
15:06:30 INFO     iteration=33000 loss=0.00426574
15:06:30 INFO     iteration=33000 loss=0.00426574
15:06:30 INFO     iteration=33000 loss=0.00426574
15:06:30 INFO     iteration=33000 loss=0.00426574
15:06:30 INFO     iteration=33000 loss=0.00426574
15:06:30 INFO     iteration=33000 loss=0.00426574
15:06:30 INFO     iteration=33000 loss=0.00426574
15:06:31 INFO     iteration=33000 loss=0.00426574
15:06:31 INFO     iteration=33000 loss=0.00426574
15:06:31 INFO     iteration=33000 loss=0.00426574
15:06:31 INFO     iteration=33000 loss=0.00426574
15:06:31 INFO     iteration=33000 loss=0.00426574
15:06:31 INFO     iteration=33000 loss=0.00426574
15:06:31 INFO     iteration=33000 loss=0.00426574
15:06:32 INFO     iteration=33000 loss=0.00426574
15:06:32 INFO     iteration=33000 loss=0.00426574
15:06:32 INFO     iteration=33000 loss=0.00426574
15:06:32 INFO     iteration=33000 loss=0.00426574
15:06:32 INFO     iteration=33000 loss=0.00426574
15:06:32 INFO     iteration=33000 loss=0.00426574
15:06:32 INFO     iteration=33000 loss=0.00426574
cp: cannot create regular file 'data/mydata/experiments/main/debug/config.json': No such file or directory
15:06:33 INFO     iteration=33000 loss=0.00426574
15:06:33 INFO     =========== Cleaning the dataset ===========
15:06:33 INFO      Config path: data/mydata/transforms_test.json
15:06:33 INFO      Config frame number: 450
15:06:33 INFO      Config sampled frames number: 450
15:06:33 SUCCESS  Loaded 450 images after 0s
15:06:33 INFO       cam_aabb=[min=[0.22734,0.134207,2.14591], max=[0.657682,0.746922,2.47912]]
15:06:34 INFO     Loading meshes!
15:06:34 SUCCESS  Loaded 450 meshes after 0s
15:06:34 SUCCESS  Recording has started!`

**Comment by Zielon** [comment]
`"render_from_snapshot": true`

**Comment by Qinerrrrr** [comment]
Thank you so much!!!

**Comment by Qinerrrrr** [comment]
> `"render_from_snapshot": true` is only for snapshots. In the other case, the recording should start automatically after max_steps.

I generate depth data using `rta::Recorder::save_depth` and i get some `*.bin` files. How do I read this type of file? Can I obtain face normal maps and meshes through existing code?

**Comment by Zielon** [comment]
```
    def read_binary(self, path):
        x = np.fromfile(path, dtype=np.uint32)
        x = x.reshape((512, 512, 1)) / 1000
        return x
 ```
