### ISSUE TITLE
OptiX incompatibility

### ISSUE THREAD

**Issue by svrakiss** [Zielon/INSTA#11]
- Windows 11
- OptiX 7.7
- Vulkan 1.3
- Cuda 12.1
- RTX 3090
- Python 3.11
-  here's the installed packages:
`colorama==0.4.6
commentjson==0.9.0
imageio==2.28.1
lark-parser==0.7.8
numpy==1.23.5
opencv-python==4.7.0.72
Pillow==9.5.0
pybind11==2.10.4
pyquaternion==0.9.9
scipy==1.10.1
tqdm==4.65.0
`

I followed the installation instructions with a few changes to the Cmakelists.txt, namely, replacing the regular `find_package(PythonLibs)` with `find_package(Python 3.7 COMPONENTS Interpreter Development)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/instant-ngp/dependencies/pybind11")`
I was able to compile the current instant-ngp repo, but not this one.  
the error i get is `fatal error C1083: Cannot open include file:
 'fmt/core.h': No such file or directory`
[cmake_output.log](https://github.com/Zielon/INSTA/files/11416033/cmake_output.log)

 I moved past that by reintroducing `    get_target_property(TCNN_INCLUDE_DIRECTORIES tiny-cuda-nn INCLUDE_DIRECTORIES)
	target_include_directories(optix_program PUBLIC ${NGP_INCLUDE_DIRECTORIES} ${TCNN_INCLUDE_DIRECTORIES})
`
into the CMakeLists.txt, but that also led to an error, suggesting an incompatibility with the OptiX library. I noticed that in the instant-ngp repo they manually supplied the optix header files, which seems to avoid this. https://github.com/NVlabs/instant-ngp/commit/c14da84edca10546594b5169fd79d9535e64a4c4 
So is there a strict dependency on a certain version of OptiX for this repo? If so, which one do I install?
Here's the log from immediately after modifying the CMakeLists.txt
[cmake_output2.log](https://github.com/Zielon/INSTA/files/11416039/cmake_output2.log)
and here's the log from subsequent build attempts.
[cmake_output3.log](https://github.com/Zielon/INSTA/files/11416040/cmake_output3.log)

**Comment by Zielon** [comment]
OptiX is not required by INSTA. You can ignore it.
