### ISSUE TITLE
Rendering the full dataset

### ISSUE THREAD

**Issue by jsaunders909** [Zielon/INSTA#12]
Really amazing work! I want to try some image-to-image translation on the final renderings to improve the final quality and add the background back in. To do this, I want to create a paired dataset of real video frames and the corresponding INSTA renderings. But, when I try to render a scene using: 

./build/rta --config insta.json --scene data/obama/transforms_train.json --snapshot data/obama/snapshot.msgpack --no-gui --height 512 --width 512

and 

"render_novel_trajectory": false,
"render_from_snapshot": true (I've tried false here as well)

Only the test set is rendered. Is it possible to render the full dataset, including the trainset?

**Comment by Zielon** [comment]
You can copy `transforms_train.json` and rename it to `transforms_test.json`.
