### ISSUE TITLE
Creating own dataset issue

### ISSUE THREAD

**Issue by ron2sun** [Zielon/INSTA#14]
When creating my own dataset in the [simplification.py](https://github.com/Zielon/INSTA/blob/master/scripts/simplification.py) file  , I am getting an error:

`ValueError: shape mismatch: value array of shape (4065,3) could not be broadcast to indexing result of shape (5023,3)`

This occurs at [This Line](https://github.com/Zielon/INSTA/blob/9e31e1221b35245b28b3b61360d774e286d53943/scripts/simplification.py#L14)

Any ideas on how to fix it?

**Comment by Zielon** [comment]
This file works only with FLAME topology. You can skip this step if you are working with a different mesh. The script only simplifies the eyeballs and regions around the eyes.
