### ISSUE TITLE
Question about Telepresence

### ISSUE THREAD

**Issue by joshualiu23** [Zielon/INSTA#15]
Hello, thank for your great work. I am currently working on building an live avatar system for Telepresence. Given the live recorded RGB video and tracked 3D mesh, we create and render the avatar in real-time. I think INSTA is very suitable for our scenario. The training time is very slow. The main problem is that the RGB video and mesh is pre-recorded. Could you give me some suggestions on how to enable real-time scenarios?

I have some a few guesses. 

1. We first train a model using 2-3min RGB video and tracked mesh. As quality loss is acceptable, then we directly use the model for new-generated RGB video and mesh in real-time. Or we re-train the model using new-generated RGB video and mesh in real-time. 

2. As the 2D video is transmitted as video chunk (1s). We train a single model for each video chunk and send the model to the user. But I guess the quality will be greatly reduced as the training set uses videos of 2-3min.

Thank you for your time. Any suggestions and comment is truly appreciable.

**Comment by Zielon** [comment]
I would train the model first. Then send the checkpoint to the user on the other side of the wire. Finally, during conversation I would send FLAME expression codes per frame for rendering (this is around 70 float numbers which is very light). Eventually, from time to time send a keyframe which could be used to improve the avatar on the other side.
