### ISSUE TITLE
Images are not getting generated as expected

### ISSUE THREAD

**Issue by alchemician** [Zielon/INSTA#16]
![00000](https://github.com/Zielon/INSTA/assets/93725624/b0940e0d-4d51-4fde-8156-ccf5b7a86866)

For some reason the images generated are not good, above attached is an image from the overlay folder.

**Comment by Zielon** [comment]
You would need to provide more information.

**Comment by alchemician** [comment]
This is a mistake on my side about absolute paths. 

Also, @Zielon it would be useful if you can modify generate.sh such that we can run it from main folder instead of scripts. It's usually a good practice to run everything from root folder
