### ISSUE TITLE
How can I find the GUI and the results?

### ISSUE THREAD

**Issue by muximuxi** [Zielon/INSTA#18]
when I use the demo checkpoint to load the data in WSL ubuntu:
./build/rta --config insta.json --scene data/obama/transforms_test.json --snapshot data/obama/snapshot.msgpack
and there is no GUI show, and where is the person's 3D models or results something, can you help me please?

**Comment by Zielon** [comment]
The output of the training, including rendered frames, checkpoint, etc will be saved in the `./data/{actor}/experiments/{config}/debug`.
