### ISSUE TITLE
About the mesh to .obj file

### ISSUE THREAD

**Issue by muximuxi** [Zielon/INSTA#20]
when I use ./build/rta Loading from a checkpoint, and I want to keep training ,it seems can not training always. or I need click the "start training", but it only can train few steps, then stop training, how can I fix this?
And another question is, when I use this GUI export mesh obj file , the result is very bad , do you have any suggestion?

**Comment by Zielon** [comment]
You can change the number of steps in the configuration file. I didn't update the code to generate/export mesh. This function is not officially supported.

**Comment by muximuxi** [comment]
So may I ask you another question, can I use this files which in experiments/insta/debug/... in other 3D modeling software？or how can I use these result? thank you very much! (It seems only the .obj file which generated with tracker.py can be used in the 3D modeling software)
