### ISSUE TITLE
Can I through load the checkpoint to keep training?

### ISSUE THREAD

**Issue by muximuxi** [Zielon/INSTA#21]
I have finished the training model , but I want to training more steps (for example max_steps=45), when I use --config insta.json --scene data/obama/transforms_test.json --snapshot data/obama/snapshot.msgpack to training , and I also reset the max_steps(max_steps=100) more than before,  but it seems can not training ,the iteration always the same number:
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
08:37:50 INFO     iteration=46 loss=0.0202575
....
and can't stop.

**Comment by kike-0304** [comment]
Me too, how did you solve it？

**Comment by Zielon** [comment]
I haven't implemented this feature.
