### ISSUE TITLE
Discrepancy in Parsing Results of face-parsing.PyTorch

### ISSUE THREAD

**Issue by RainbowRui** [Zielon/INSTA#22]
Hello,

First of all, I would like to commend you on the excellent work you have done. It has provided valuable insights for related research.

While processing my own data using the face-parsing.PyTorch library (https://github.com/zllrunning/face-parsing.PyTorch), I noticed that the parsing results differed from your given examples. In the source code, a face is divided into multiple colors, creating a multicolored representation. You can see an example of this below:
![image](https://github.com/Zielon/INSTA/assets/39452932/967833ea-9c54-4032-af25-e0333f79dc5d)

However, the given examples showcase parsing colors that primarily consist of different levels of red, as shown in the following image:
![00267](https://github.com/Zielon/INSTA/assets/39452932/39859104-aa28-4c94-a0a1-2b0938d22604)

This leads me to inquire about the new part_colors variable in the face-parsing.PyTorch/test.py script of your project. I believe it plays a significant role in achieving the final optimized results.

Thank you for your attention, and I look forward to your response.

Best regards.

**Comment by Zielon** [comment]
Hello, yes, I am using different labels. To generate the correct input, you can follow the instructions from here: https://github.com/Zielon/INSTA#dataset-generation. Or take a look at the git patch: https://github.com/Zielon/INSTA/blob/master/scripts/patches/face-parsing#L55C1-L55C1.

**Comment by RainbowRui** [comment]
Thanks a lot! It works!
