### ISSUE TITLE
FullyFusedMLP is not supported

### ISSUE THREAD

**Issue by mengcius** [Zielon/INSTA#23]
I have the following warning when I run it, but it works, will it affect the effect?

`Warning: FullyFusedMLP is not supported for the selected architecture 70. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.`

**Comment by mengcius** [comment]
And when I use your snapshot.msgpack I get an error:
` ERROR    Uncaught exception: Can't set params because CPU buffer has the wrong size.`

**Comment by Zielon** [comment]
It looks like you are using different GPU than me. I was training the model on RTX3090.
