### ISSUE TITLE
When I run the second step, the program keeps running and cannot be stopped. 

### ISSUE THREAD

**Issue by kike-0304** [Zielon/INSTA#27]
When I run the second step, the program keeps running and cannot be stopped. My command is 
./build/rta --config insta.json --scene data/obama/transforms_test.json --snapshot data/obama/snapshot.msgpack --no-gui

**Comment by haonanhe** [comment]
same. Have you solved it? @kike-0304

**Comment by itxtayab** [comment]
same issue
