### ISSUE TITLE
Reenactment failure: the number of faces (8090) of provided canonical.obj is not equal to that of mesh (9766) from Metrical Photometric Tracker 

### ISSUE THREAD

**Issue by tsuJohc** [Zielon/INSTA#28]
Hi, thanks for sharing the excellent work!

I want to reenact the provided avatar with new expressions. So I need to use _Metrical Photometric Tracker_ to track FLAME parameters of expression `a` from a video of another avatar and generate the mesh with the combination of canonical shape parameters and expression parameters of expression `a`.

However, the strange thing is that the number of faces(8090) of canonical mesh provided is not equal to that (9766) of output mesh from _Metrical Photometric Tracker_. I also found that the number of faces of output mesh from [DECA](https://github.com/yfeng95/DECA) is also 9766. Do you have any ideas on this problem?

Besides, could you please provide the FLAME parameters of each frame and canonical shape parameter in your dataset, which will make the reenactment easier (if so, no FLAME tracker is needed)?

**Comment by Zielon** [comment]
True, sorry for the confusion. INSTA uses a different number of faces. You can use this script to generate correct input geometry: https://github.com/Zielon/INSTA/blob/master/scripts/simplification.py.
