### ISSUE TITLE
about training INSTA

### ISSUE THREAD

**Issue by flyingshan** [Zielon/INSTA#3]
hello, 
I am trying to train an avatar using INSTA. I disable the gui option using --no-gui since there is no gui on my machine. I wonder how to set the training steps and visualize the results?

**Comment by lsx0101** [comment]
same question

**Comment by haithemb** [comment]
same question. Instant ngp (on which INSRTA in built) allows for offscreen rendering for recording videos from different camera point of view. It seems that INSTA only records from screen. Would it possible to add this so that it works on a headless machine? Thanks!

**Comment by Zielon** [comment]
Soon I will release headless training option.

**Comment by Zielon** [comment]
The `--no-gui` option should now work. Please read README how to use the config options for training.

**Comment by muximuxi** [comment]
Can you set the train steps via insta.json "max_steps": 33000?
I followed the Usage and Requirements, but it didn't work, it can't training , and just show the the Recording frame in the mode horizontal/overlay/normals/.

**Comment by lsx0101** [comment]
> Can you set the train steps via insta.json "max_steps": 33000? I followed the Usage and Requirements, but it didn't work, it can't training , and just show the the Recording frame in the mode horizontal/overlay/normals/.

it works for me. you may set something worng.

**Comment by muximuxi** [comment]
> 

set the "render_from_snapshot": false , then it works. thanks
