### ISSUE TITLE
Could you provide the 3DMM shape coefficient `identity.npy` of each dataset?

### ISSUE THREAD

**Issue by tsuJohc** [Zielon/INSTA#31]
Hi, Thanks for sharing the excellent work!

Now, I am going to perform a face reenactment. The provided datasets contain the 3DMM expression coefficient and camera pose of each frame. However, the 3DMM shape coefficient is not provided for each dataset. I use the `MICA` in README.md to estimate the shape coefficient, but the results are not satisfied since there is always a bias toward the `canonical.obj` you provided.

Therefore, I am wondering if you could provide the 3DMM shape coefficient `identity.npy` of each dataset (not for each frame) ?

**Comment by Zielon** [comment]
identity.npy should be per sequence not per frame. Which exactly dataset are you using?
