### ISSUE TITLE
Controlling expressions via FLAME

### ISSUE THREAD

**Issue by jackykwe** [Zielon/INSTA#32]
From issue #6, it was mentioned that for expression transfer, we need the new meshes corresponding to the new expressions. How do we obtain the meshes from desired FLAME expressions?

I've seen that length-100 FLAME vectors are used, but I can't get them to affect the expression of the output video.

**Comment by Zielon** [comment]
You could run a tracker on a new sequence to get the expressions and then use relative transfer between actors.
