### ISSUE TITLE
Create data with shoulders

### ISSUE THREAD

**Issue by chiehwangs** [Zielon/INSTA#33]
Hi, 

I made the data with just the head and neck and it ran successfully, but how do I go further and make the data with the shoulders?  Only need to modify the mask in postprocess.py?

best,
chieh

**Comment by Zielon** [comment]
Hey Chieh, if you provide images with shoulders for training it should be enough, however, the method was not designed to handle shoulders. To get those images, you just need to change the segmentation map generation. Here are the parts https://github.com/Zielon/INSTA/blob/master/scripts/patches/face-parsing#L55. You need to change the code https://github.com/Zielon/INSTA/blob/master/scripts/generate.sh in the corresponding modules.
