### ISSUE TITLE
Bad Results 

### ISSUE THREAD

**Issue by maocaixia** [Zielon/INSTA#35]
Any Suggestion about How to improve it. 

obama drive nf_01

https://github.com/Zielon/INSTA/assets/23650992/5448b501-5295-4581-81e4-1d33ab28a26c

duda drive obama 

https://github.com/Zielon/INSTA/assets/23650992/1cadba12-0891-4c9a-80a9-91a4802db123

nf_01 drive nf_01 

https://github.com/Zielon/INSTA/assets/23650992/e77e35e8-8853-48ce-8abc-09f76118e22a

**Comment by Zielon** [comment]
You would need to provide more context. Is this the dataset that I provided?

**Comment by maocaixia** [comment]
Yes, I use the script like this. 

./build/rta --config insta.json --scene data/duda/transforms_test.json --snapshot data/obama/snapshot.msgpack

@Zielon

**Comment by maocaixia** [comment]
If I use the same person's posture information to drive, the results will be better. If use one person's posture to drive another person, the results will be worse.

**Comment by Zielon** [comment]
You need to correctly transfer expressions. To do that you need to transfer only relative expressions, for instance, select a neutral expression and then transfer the residuals to the next actor for which you do the same (its neutral expressions + delta expression from the source actor).

**Comment by maocaixia** [comment]
Would you give some examples? if I want to use the duda expressions to drive the obama, What exactly do I need to do?

**Comment by heiha324** [comment]
Have you solved this problem？

**Comment by Zielon** [comment]
#37 Please take a look here.
