### ISSUE TITLE
Could you please release the test dataset with the same neck as train dataset

### ISSUE THREAD

**Issue by HarshWinterBytes** [Zielon/INSTA#39]
Wonderful work and nice dataset!
But I find the neck in the test dataset is different from the train dataset which will lead a bad metric results as the model is not trained with the larger neck. 
So could please tell me how to get the same neck in train dataset or release the test dataset which has the same neck with the train dataset.
Thanks a lot!

**Comment by Zielon** [comment]
Hello, I will update the dataset such that it will contain the original images w/o the neck cropping. Thank you for raising the problem.

**Comment by Zielon** [comment]
The updated dataset is now available.
