### ISSUE TITLE
Accessible of Girls Datasets in your paper？

### ISSUE THREAD

**Issue by Lxiangyue** [Zielon/INSTA#40]
Hi, zielon, many thanks for your great work! It's pretty awesome!

May I inquire if you could open-source the girl's datasets utilized in your paper? Cause I noticed that all datasets you released are men. I think only men may bring some potential sexism issues.

Looking forward to your reply! Many Thanks!

Best,
Xiangyue

**Comment by Zielon** [comment]
Hello, thank you for the comment. I wish to release all the data that I have collected, unfortunately, not everyone agreed on releasing their videos and data thus the available dataset contains only people who gave me their written permission.
