### ISSUE TITLE
Accessible of the same format dataset of "yufeng"?

### ISSUE THREAD

**Issue by Lxiangyue** [Zielon/INSTA#41]
Hi, zielon, many thanks for your reply! I fully understand that we need everyone to agree on releasing their data.

In that case, could you please provide the processed data of "yufeng" in IMavatar? I noticed that you also trained this model in your paper. But it's datasets are not aligned with your format.  

Looking forward to your reply! Many Thanks!

Best,
Xiangyue

**Comment by Zielon** [comment]
Unfortunately, I currently do not have it processed. However, all you need is to run the tracker on that sequence https://github.com/Zielon/metrical-tracker and it should work just fine.
