### ISSUE TITLE
Why only first 16 expression is used?

### ISSUE THREAD

**Issue by ChikaYan** [Zielon/INSTA#42]
Hi, thanks for the great work and amazing code! I have a small question -- it seems when loading the expression from txt file, only first 16 digits are kept. May I ask what are those first 16 digits, and why this is done?

https://github.com/Zielon/INSTA-pytorch/blob/e680e492822d6308f272fa7d6b46ea7f86fc78c0/insta/provider.py#L277

Many thanks!

**Comment by GhostCai** [comment]
Hi! I think the reason is that the first 16 coefficients are sufficient for most expressions?
