### ISSUE TITLE
Bug report on the dataset preprocessing script

### ISSUE THREAD

**Issue by zjumsj** [Zielon/INSTA#48]
Thanks to the author for the great work! There may be some minor issues in the dataset preprocessing code.
The suspected bug is near line 168 in scripts/transforms.py

```python
with Pool(processes=8) as pool:
    params = [(frames[i], src, output) for i in range(len(frames))]
    for task in tqdm(pool.imap_unordered(dump_frame, params), total=len(frames)):
        if task is not None:
            data['frames'].append(task)
```

**Negtive impact:** The order returned by imap_unordered is randomized, so the final 350 frames obtained may not correspond to the last 350 frames of the video. When comparing with other works (which also take the last 350 frames of the video), alignment issues may be observed.

**Bugfix:** Here is the fixed version
```python
data['frames'] = [None] * len(frames)
with Pool(processes=8) as pool:
    params = [(frames[i], src, output) for i in range(len(frames))]
    for task in tqdm(pool.imap_unordered(dump_frame, params), total=len(frames)):
        if task is not None:
            id = int(os.path.basename(task['file_path'])[:5])
            data['frames'][id] = task
```

 See also my attached patch.

[transforms.patch](https://github.com/user-attachments/files/17944972/transforms.patch)

**Comment by Zielon** [comment]
This is a good catch. Thank you. Let me fix it.
