### ISSUE TITLE
Running INSTA on light stage capture data.

### ISSUE THREAD

**Issue by preddy5** [Zielon/INSTA#5]
Hey @Zielon
Congrats on the great work and thank you for releasing the code.
I am trying to use INSTA on data captured in a light stage setting. I was able to successfully run MICA on the dataset however metrical-tracker does not perform well on the data because of the obvious reasons. What would be the best way to adopt INSTA to date captured using a light stage system? Thank you.

Regards,
Pradyumna.

**Comment by Zielon** [comment]
Hello Pradyumna,

that would not be straightforward. If I were you, I would start investigating work that aims NERF from [multiview data](https://studios.disneyresearch.com/2022/07/24/morf-morphable-radiance-fields-for-multiview-neural-head-modeling/), etc. And maybe later try light stage-based relighting.
