### ISSUE TITLE
Can I use the existing code to do expression transfer

### ISSUE THREAD

**Issue by lsx0101** [Zielon/INSTA#6]
Thanks for your solution for headless trainging, it works well.
In the  Supplemental Document->B. Applications, the expression transfer results are attractive. Is it possible to do expression transfer with the existing code?

**Comment by lsx0101** [comment]
> Yes, the current code supports it, however, I did not upload the relative expression generation script. I maybe release this part as well. You just need to have the corresponding transforms.json file and meshes.

thanks for your answer. I also wanna know how to render images with existing checkpoints.

**Comment by Zielon** [comment]
You can use `"render_from_snapshot": false # For --no-gui option to directly render sequences` from the config.

**Comment by lsx0101** [comment]
> You can use `"render_from_snapshot": true # For --no-gui option to directly render sequences` from the config.

I use "render_from_snapshot":true, and set the --scene, --no-gui, --snapshot, It seems nothing happens.

**Comment by Zielon** [comment]
You are right there was a bug. Now it is fixed, you can also specify `render_novel_trajectory` option in this mode.

**Comment by lsx0101** [comment]
> You are right there was a bug. Now it is fixed, you can also specify `render_novel_trajectory` option in this mode.

It doesn't seem to work.

**Comment by Zielon** [comment]
I am using:

`--config insta.json --scene data/obama/transforms_test.json --snapshot data/obama/snapshot.msgpack --no-gui`

```
{
	"parent": "main.json",
	"max_steps": 33000,
	"max_cached_bvh": 4000,
	"max_images_gpu": 1700,
	"use_dataset_cache": true,
	"render_novel_trajectory": false,
	"render_from_snapshot": true
}
```
The output should be in `./data/obama/experiments/insta/debug/overlay` if you need more trajectories use `"render_novel_trajectory": true`

**Comment by lsx0101** [comment]
> I am using:
> 
> `--config insta.json --scene data/obama/transforms_test.json --snapshot data/obama/snapshot.msgpack --no-gui`
> 
> ```shell
> {
> 	"parent": "main.json",
> 	"max_steps": 33000,
> 	"max_cached_bvh": 4000,
> 	"max_images_gpu": 1700,
> 	"use_dataset_cache": true,
> 	"render_novel_trajectory": false,
> 	"render_from_snapshot": true
> }
> ```
> 
> The output should be in `./data/obama/experiments/insta/debug/overlay` if you need more trajectories use `"render_novel_trajectory": true`

I use the same config, the code only outputs after training. When I try to render reults again, nothing appears.

**Comment by alchemician** [comment]
@lsx0101 it is just replacing the previous files in the debug/overlay folder

**Comment by lsx0101** [comment]
> @lsx0101 it is just replacing the previous files in the debug/overlay folder

it works, but the rendering quality is not as good as training expressions
