### ISSUE TITLE
Confusion about the paper

### ISSUE THREAD

**Issue by BCL123456-BAL** [Zielon/INSTA#9]
It is a great jop!
But there's something counterintuitive.
![image](https://user-images.githubusercontent.com/75575496/231187810-87afaa9b-edcf-43a1-b616-a4bbd4b06558.png)
Why not the triangular mesh that this sampled ray hits.

**Comment by Zielon** [comment]
I might soon release a script for reenactment, so then you can check how it is done.

**Comment by Zielon** [comment]
You can but using geometry.
